// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PropertyListing is the predicate function for propertylisting builders.
type PropertyListing func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
