
# Build Stage
FROM golang:1.19-alpine3.17 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /dist

FROM alpine:latest

WORKDIR /

COPY --from=build /dist /dist

EXPOSE 8080
CMD [ "go","run","main.go" ]

ENTRYPOINT ["/dist"]
