// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NattapolChan/ent/predicate"
	"github.com/NattapolChan/ent/propertylisting"
	"github.com/NattapolChan/ent/user"
)

// PropertyListingQuery is the builder for querying PropertyListing entities.
type PropertyListingQuery struct {
	config
	ctx        *QueryContext
	order      []propertylisting.OrderOption
	inters     []Interceptor
	predicates []predicate.PropertyListing
	withUsers  *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PropertyListingQuery builder.
func (plq *PropertyListingQuery) Where(ps ...predicate.PropertyListing) *PropertyListingQuery {
	plq.predicates = append(plq.predicates, ps...)
	return plq
}

// Limit the number of records to be returned by this query.
func (plq *PropertyListingQuery) Limit(limit int) *PropertyListingQuery {
	plq.ctx.Limit = &limit
	return plq
}

// Offset to start from.
func (plq *PropertyListingQuery) Offset(offset int) *PropertyListingQuery {
	plq.ctx.Offset = &offset
	return plq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (plq *PropertyListingQuery) Unique(unique bool) *PropertyListingQuery {
	plq.ctx.Unique = &unique
	return plq
}

// Order specifies how the records should be ordered.
func (plq *PropertyListingQuery) Order(o ...propertylisting.OrderOption) *PropertyListingQuery {
	plq.order = append(plq.order, o...)
	return plq
}

// QueryUsers chains the current query on the "users" edge.
func (plq *PropertyListingQuery) QueryUsers() *UserQuery {
	query := (&UserClient{config: plq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := plq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := plq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(propertylisting.Table, propertylisting.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, propertylisting.UsersTable, propertylisting.UsersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(plq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PropertyListing entity from the query.
// Returns a *NotFoundError when no PropertyListing was found.
func (plq *PropertyListingQuery) First(ctx context.Context) (*PropertyListing, error) {
	nodes, err := plq.Limit(1).All(setContextOp(ctx, plq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{propertylisting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (plq *PropertyListingQuery) FirstX(ctx context.Context) *PropertyListing {
	node, err := plq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PropertyListing ID from the query.
// Returns a *NotFoundError when no PropertyListing ID was found.
func (plq *PropertyListingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = plq.Limit(1).IDs(setContextOp(ctx, plq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{propertylisting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (plq *PropertyListingQuery) FirstIDX(ctx context.Context) int {
	id, err := plq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PropertyListing entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PropertyListing entity is found.
// Returns a *NotFoundError when no PropertyListing entities are found.
func (plq *PropertyListingQuery) Only(ctx context.Context) (*PropertyListing, error) {
	nodes, err := plq.Limit(2).All(setContextOp(ctx, plq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{propertylisting.Label}
	default:
		return nil, &NotSingularError{propertylisting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (plq *PropertyListingQuery) OnlyX(ctx context.Context) *PropertyListing {
	node, err := plq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PropertyListing ID in the query.
// Returns a *NotSingularError when more than one PropertyListing ID is found.
// Returns a *NotFoundError when no entities are found.
func (plq *PropertyListingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = plq.Limit(2).IDs(setContextOp(ctx, plq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{propertylisting.Label}
	default:
		err = &NotSingularError{propertylisting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (plq *PropertyListingQuery) OnlyIDX(ctx context.Context) int {
	id, err := plq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PropertyListings.
func (plq *PropertyListingQuery) All(ctx context.Context) ([]*PropertyListing, error) {
	ctx = setContextOp(ctx, plq.ctx, "All")
	if err := plq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PropertyListing, *PropertyListingQuery]()
	return withInterceptors[[]*PropertyListing](ctx, plq, qr, plq.inters)
}

// AllX is like All, but panics if an error occurs.
func (plq *PropertyListingQuery) AllX(ctx context.Context) []*PropertyListing {
	nodes, err := plq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PropertyListing IDs.
func (plq *PropertyListingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if plq.ctx.Unique == nil && plq.path != nil {
		plq.Unique(true)
	}
	ctx = setContextOp(ctx, plq.ctx, "IDs")
	if err = plq.Select(propertylisting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (plq *PropertyListingQuery) IDsX(ctx context.Context) []int {
	ids, err := plq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (plq *PropertyListingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, plq.ctx, "Count")
	if err := plq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, plq, querierCount[*PropertyListingQuery](), plq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (plq *PropertyListingQuery) CountX(ctx context.Context) int {
	count, err := plq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (plq *PropertyListingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, plq.ctx, "Exist")
	switch _, err := plq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (plq *PropertyListingQuery) ExistX(ctx context.Context) bool {
	exist, err := plq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PropertyListingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (plq *PropertyListingQuery) Clone() *PropertyListingQuery {
	if plq == nil {
		return nil
	}
	return &PropertyListingQuery{
		config:     plq.config,
		ctx:        plq.ctx.Clone(),
		order:      append([]propertylisting.OrderOption{}, plq.order...),
		inters:     append([]Interceptor{}, plq.inters...),
		predicates: append([]predicate.PropertyListing{}, plq.predicates...),
		withUsers:  plq.withUsers.Clone(),
		// clone intermediate query.
		sql:  plq.sql.Clone(),
		path: plq.path,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (plq *PropertyListingQuery) WithUsers(opts ...func(*UserQuery)) *PropertyListingQuery {
	query := (&UserClient{config: plq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	plq.withUsers = query
	return plq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PropertyListing.Query().
//		GroupBy(propertylisting.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (plq *PropertyListingQuery) GroupBy(field string, fields ...string) *PropertyListingGroupBy {
	plq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PropertyListingGroupBy{build: plq}
	grbuild.flds = &plq.ctx.Fields
	grbuild.label = propertylisting.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.PropertyListing.Query().
//		Select(propertylisting.FieldName).
//		Scan(ctx, &v)
func (plq *PropertyListingQuery) Select(fields ...string) *PropertyListingSelect {
	plq.ctx.Fields = append(plq.ctx.Fields, fields...)
	sbuild := &PropertyListingSelect{PropertyListingQuery: plq}
	sbuild.label = propertylisting.Label
	sbuild.flds, sbuild.scan = &plq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PropertyListingSelect configured with the given aggregations.
func (plq *PropertyListingQuery) Aggregate(fns ...AggregateFunc) *PropertyListingSelect {
	return plq.Select().Aggregate(fns...)
}

func (plq *PropertyListingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range plq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, plq); err != nil {
				return err
			}
		}
	}
	for _, f := range plq.ctx.Fields {
		if !propertylisting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if plq.path != nil {
		prev, err := plq.path(ctx)
		if err != nil {
			return err
		}
		plq.sql = prev
	}
	return nil
}

func (plq *PropertyListingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PropertyListing, error) {
	var (
		nodes       = []*PropertyListing{}
		_spec       = plq.querySpec()
		loadedTypes = [1]bool{
			plq.withUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PropertyListing).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PropertyListing{config: plq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, plq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := plq.withUsers; query != nil {
		if err := plq.loadUsers(ctx, query, nodes,
			func(n *PropertyListing) { n.Edges.Users = []*User{} },
			func(n *PropertyListing, e *User) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (plq *PropertyListingQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*PropertyListing, init func(*PropertyListing), assign func(*PropertyListing, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*PropertyListing)
	nids := make(map[string]map[*PropertyListing]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(propertylisting.UsersTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(propertylisting.UsersPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(propertylisting.UsersPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(propertylisting.UsersPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*PropertyListing]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "users" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (plq *PropertyListingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := plq.querySpec()
	_spec.Node.Columns = plq.ctx.Fields
	if len(plq.ctx.Fields) > 0 {
		_spec.Unique = plq.ctx.Unique != nil && *plq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, plq.driver, _spec)
}

func (plq *PropertyListingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(propertylisting.Table, propertylisting.Columns, sqlgraph.NewFieldSpec(propertylisting.FieldID, field.TypeInt))
	_spec.From = plq.sql
	if unique := plq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if plq.path != nil {
		_spec.Unique = true
	}
	if fields := plq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, propertylisting.FieldID)
		for i := range fields {
			if fields[i] != propertylisting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := plq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := plq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := plq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := plq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (plq *PropertyListingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(plq.driver.Dialect())
	t1 := builder.Table(propertylisting.Table)
	columns := plq.ctx.Fields
	if len(columns) == 0 {
		columns = propertylisting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if plq.sql != nil {
		selector = plq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if plq.ctx.Unique != nil && *plq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range plq.predicates {
		p(selector)
	}
	for _, p := range plq.order {
		p(selector)
	}
	if offset := plq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := plq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PropertyListingGroupBy is the group-by builder for PropertyListing entities.
type PropertyListingGroupBy struct {
	selector
	build *PropertyListingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (plgb *PropertyListingGroupBy) Aggregate(fns ...AggregateFunc) *PropertyListingGroupBy {
	plgb.fns = append(plgb.fns, fns...)
	return plgb
}

// Scan applies the selector query and scans the result into the given value.
func (plgb *PropertyListingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, plgb.build.ctx, "GroupBy")
	if err := plgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PropertyListingQuery, *PropertyListingGroupBy](ctx, plgb.build, plgb, plgb.build.inters, v)
}

func (plgb *PropertyListingGroupBy) sqlScan(ctx context.Context, root *PropertyListingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(plgb.fns))
	for _, fn := range plgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*plgb.flds)+len(plgb.fns))
		for _, f := range *plgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*plgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := plgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PropertyListingSelect is the builder for selecting fields of PropertyListing entities.
type PropertyListingSelect struct {
	*PropertyListingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pls *PropertyListingSelect) Aggregate(fns ...AggregateFunc) *PropertyListingSelect {
	pls.fns = append(pls.fns, fns...)
	return pls
}

// Scan applies the selector query and scans the result into the given value.
func (pls *PropertyListingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pls.ctx, "Select")
	if err := pls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PropertyListingQuery, *PropertyListingSelect](ctx, pls.PropertyListingQuery, pls, pls.inters, v)
}

func (pls *PropertyListingSelect) sqlScan(ctx context.Context, root *PropertyListingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pls.fns))
	for _, fn := range pls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
