// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NattapolChan/ent/predicate"
	"github.com/NattapolChan/ent/propertylisting"
)

// PropertyListingDelete is the builder for deleting a PropertyListing entity.
type PropertyListingDelete struct {
	config
	hooks    []Hook
	mutation *PropertyListingMutation
}

// Where appends a list predicates to the PropertyListingDelete builder.
func (pld *PropertyListingDelete) Where(ps ...predicate.PropertyListing) *PropertyListingDelete {
	pld.mutation.Where(ps...)
	return pld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pld *PropertyListingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pld.sqlExec, pld.mutation, pld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pld *PropertyListingDelete) ExecX(ctx context.Context) int {
	n, err := pld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pld *PropertyListingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(propertylisting.Table, sqlgraph.NewFieldSpec(propertylisting.FieldID, field.TypeInt))
	if ps := pld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pld.mutation.done = true
	return affected, err
}

// PropertyListingDeleteOne is the builder for deleting a single PropertyListing entity.
type PropertyListingDeleteOne struct {
	pld *PropertyListingDelete
}

// Where appends a list predicates to the PropertyListingDelete builder.
func (pldo *PropertyListingDeleteOne) Where(ps ...predicate.PropertyListing) *PropertyListingDeleteOne {
	pldo.pld.mutation.Where(ps...)
	return pldo
}

// Exec executes the deletion query.
func (pldo *PropertyListingDeleteOne) Exec(ctx context.Context) error {
	n, err := pldo.pld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{propertylisting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pldo *PropertyListingDeleteOne) ExecX(ctx context.Context) {
	if err := pldo.Exec(ctx); err != nil {
		panic(err)
	}
}
