// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/NattapolChan/ent/predicate"
	"github.com/NattapolChan/ent/propertylisting"
	"github.com/NattapolChan/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetName sets the "name" field.
func (uu *UserUpdate) SetName(s string) *UserUpdate {
	uu.mutation.SetName(s)
	return uu
}

// SetEmailAddr sets the "emailAddr" field.
func (uu *UserUpdate) SetEmailAddr(s string) *UserUpdate {
	uu.mutation.SetEmailAddr(s)
	return uu
}

// SetFavorites sets the "favorites" field.
func (uu *UserUpdate) SetFavorites(s []string) *UserUpdate {
	uu.mutation.SetFavorites(s)
	return uu
}

// AppendFavorites appends s to the "favorites" field.
func (uu *UserUpdate) AppendFavorites(s []string) *UserUpdate {
	uu.mutation.AppendFavorites(s)
	return uu
}

// AddPropertylistingIDs adds the "propertylistings" edge to the PropertyListing entity by IDs.
func (uu *UserUpdate) AddPropertylistingIDs(ids ...int) *UserUpdate {
	uu.mutation.AddPropertylistingIDs(ids...)
	return uu
}

// AddPropertylistings adds the "propertylistings" edges to the PropertyListing entity.
func (uu *UserUpdate) AddPropertylistings(p ...*PropertyListing) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.AddPropertylistingIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearPropertylistings clears all "propertylistings" edges to the PropertyListing entity.
func (uu *UserUpdate) ClearPropertylistings() *UserUpdate {
	uu.mutation.ClearPropertylistings()
	return uu
}

// RemovePropertylistingIDs removes the "propertylistings" edge to PropertyListing entities by IDs.
func (uu *UserUpdate) RemovePropertylistingIDs(ids ...int) *UserUpdate {
	uu.mutation.RemovePropertylistingIDs(ids...)
	return uu
}

// RemovePropertylistings removes "propertylistings" edges to PropertyListing entities.
func (uu *UserUpdate) RemovePropertylistings(p ...*PropertyListing) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.RemovePropertylistingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UserUpdate) check() error {
	if v, ok := uu.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := uu.mutation.EmailAddr(); ok {
		if err := user.EmailAddrValidator(v); err != nil {
			return &ValidationError{Name: "emailAddr", err: fmt.Errorf(`ent: validator failed for field "User.emailAddr": %w`, err)}
		}
	}
	return nil
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := uu.mutation.EmailAddr(); ok {
		_spec.SetField(user.FieldEmailAddr, field.TypeString, value)
	}
	if value, ok := uu.mutation.Favorites(); ok {
		_spec.SetField(user.FieldFavorites, field.TypeJSON, value)
	}
	if value, ok := uu.mutation.AppendedFavorites(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldFavorites, value)
		})
	}
	if uu.mutation.PropertylistingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.PropertylistingsTable,
			Columns: user.PropertylistingsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertylisting.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedPropertylistingsIDs(); len(nodes) > 0 && !uu.mutation.PropertylistingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.PropertylistingsTable,
			Columns: user.PropertylistingsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertylisting.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.PropertylistingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.PropertylistingsTable,
			Columns: user.PropertylistingsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertylisting.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetName sets the "name" field.
func (uuo *UserUpdateOne) SetName(s string) *UserUpdateOne {
	uuo.mutation.SetName(s)
	return uuo
}

// SetEmailAddr sets the "emailAddr" field.
func (uuo *UserUpdateOne) SetEmailAddr(s string) *UserUpdateOne {
	uuo.mutation.SetEmailAddr(s)
	return uuo
}

// SetFavorites sets the "favorites" field.
func (uuo *UserUpdateOne) SetFavorites(s []string) *UserUpdateOne {
	uuo.mutation.SetFavorites(s)
	return uuo
}

// AppendFavorites appends s to the "favorites" field.
func (uuo *UserUpdateOne) AppendFavorites(s []string) *UserUpdateOne {
	uuo.mutation.AppendFavorites(s)
	return uuo
}

// AddPropertylistingIDs adds the "propertylistings" edge to the PropertyListing entity by IDs.
func (uuo *UserUpdateOne) AddPropertylistingIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddPropertylistingIDs(ids...)
	return uuo
}

// AddPropertylistings adds the "propertylistings" edges to the PropertyListing entity.
func (uuo *UserUpdateOne) AddPropertylistings(p ...*PropertyListing) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.AddPropertylistingIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearPropertylistings clears all "propertylistings" edges to the PropertyListing entity.
func (uuo *UserUpdateOne) ClearPropertylistings() *UserUpdateOne {
	uuo.mutation.ClearPropertylistings()
	return uuo
}

// RemovePropertylistingIDs removes the "propertylistings" edge to PropertyListing entities by IDs.
func (uuo *UserUpdateOne) RemovePropertylistingIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemovePropertylistingIDs(ids...)
	return uuo
}

// RemovePropertylistings removes "propertylistings" edges to PropertyListing entities.
func (uuo *UserUpdateOne) RemovePropertylistings(p ...*PropertyListing) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.RemovePropertylistingIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UserUpdateOne) check() error {
	if v, ok := uuo.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.EmailAddr(); ok {
		if err := user.EmailAddrValidator(v); err != nil {
			return &ValidationError{Name: "emailAddr", err: fmt.Errorf(`ent: validator failed for field "User.emailAddr": %w`, err)}
		}
	}
	return nil
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := uuo.mutation.EmailAddr(); ok {
		_spec.SetField(user.FieldEmailAddr, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Favorites(); ok {
		_spec.SetField(user.FieldFavorites, field.TypeJSON, value)
	}
	if value, ok := uuo.mutation.AppendedFavorites(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldFavorites, value)
		})
	}
	if uuo.mutation.PropertylistingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.PropertylistingsTable,
			Columns: user.PropertylistingsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertylisting.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedPropertylistingsIDs(); len(nodes) > 0 && !uuo.mutation.PropertylistingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.PropertylistingsTable,
			Columns: user.PropertylistingsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertylisting.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.PropertylistingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.PropertylistingsTable,
			Columns: user.PropertylistingsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertylisting.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
